name: Deploy to GitHub Pages (Static HTML)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Copy everything (except .git/.github) into a publish folder
      - name: Prepare files
        run: |
          mkdir public
          shopt -s extglob
          # Copy everything except .git/.github into public
          cp -r !(public|.git|.github) public || true

          # If your main HTML has a different name, copy it to index.html
          if [ -f "ps_clarity_companion_WORKING - Copy.html" ]; then
            cp "ps_clarity_companion_WORKING - Copy.html" public/index.html
          fi

          # SPA fallback (harmless even if not a SPA)
          if [ -f public/index.html ]; then
            cp public/index.html public/404.html
          fi


      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: false
